# -*- coding: utf-8 -*-

name: CI Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:

  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Install singular
      run: |
        sudo apt-get update
        sudo apt-get install singular
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Checkout this Repo
      uses: actions/checkout@v2
      with:
        path: syngular-dev
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with flake8
      run: |
        cd syngular-dev
        flake8 syngular/ --count --max-line-length=190 --statistics --verbose
